'use client';
import { useRouter } from '@payloadcms/ui';
import { Banner, Button, Card, CheckRow, Checklist, ConfirmDestructive, CopyButton, DataTable, KeyValueList, MaskedValue, Pagination, SignageBand, Timestamp, type ColumnDef } from '@acme/ui/admin';
import { Heading, Link, Paragraph, Section } from '@acme/ui/html';
import { cancelCallerDeletion, deleteConsentRecord, removeStaff, resendConsentEmail, reveal, runIntegrityCheck, scheduleCallerDeletion } from '../api';
import { consoleCopy, reasonOptions } from '../copy';
import { useCallersStore, useConsentStore, useOverviewStore, useSettingsStore } from '../stores';
import { ConsoleShell } from '../Shell';

const api = { baseUrl: '/payload-api' } as const;
const fail = () => new Error(consoleCopy.errors.action);
type Integrity = { at: string; sharedEgg: number; idMismatch: number; orphans: number; staleReady: number };
type EventRow = { id: string; at: string; action: string; target: string };
const eventColumns: ColumnDef<EventRow, unknown>[] = [{ accessorKey: 'at', header: 'When', cell: ({ row }) => <Timestamp at={new Date(row.original.at)} format="both" /> }, { accessorKey: 'action', header: 'Action' }, { accessorKey: 'target', header: 'Target' }];

export function OverviewViewClient({ counts, run, events }: { counts: { consents: number; eggs: number; mons: number }; run: Integrity | null; events: EventRow[] }) {
  const router = useRouter(); const dialog = useOverviewStore((s) => s.dialog); const open = useOverviewStore((s) => s.openDialog); const close = useOverviewStore((s) => s.closeDialog);
  const failures = run ? run.sharedEgg + run.idMismatch + run.orphans + run.staleReady : 0;
  return <ConsoleShell section="overview" heading={consoleCopy.overview.heading}><SignageBand tone={failures ? 'danger' : 'signage'} headline={failures ? `${failures} duplicated Mons` : consoleCopy.overview.healthy} detail={run ? `Checked ${new Date(run.at).toLocaleString()}` : undefined} action={<Button title={consoleCopy.overview.run} onPress={async () => { open('run'); const result = await runIntegrityCheck(api); close(); if (result.ok) router.refresh(); }} />} /><Section className="grid gap-4 md:grid-cols-3"><Card surface="page" title="Consents pending" description={String(counts.consents)} /><Card surface="page" title="Eggs incubating" description={String(counts.eggs)} /><Card surface="page" title="Mons" description={String(counts.mons)} /></Section><Section><Heading level={2}>{consoleCopy.overview.recent}</Heading><DataTable surface="page" caption={consoleCopy.overview.recent} data={events} columns={eventColumns} getRowId={(row) => row.id} /></Section>{dialog === 'run' ? <Paragraph>Checking…</Paragraph> : null}</ConsoleShell>;
}

type Caller = { id: string; email: string; name: string; age: string; consent: string; joined: string; updatedAt: string; deletionScheduledFor: string | null };
const callerColumns: ColumnDef<Caller, unknown>[] = [{ accessorKey: 'id', header: 'Caller' }, { accessorKey: 'age', header: 'Age band' }, { accessorKey: 'consent', header: 'Consent' }, { accessorKey: 'joined', header: 'Joined', cell: ({ row }) => <Timestamp at={new Date(row.original.joined)} format="relative" /> }];
export function CallersViewClient({ callers, selectedId, page, pageCount, totalCount }: { callers: Caller[]; selectedId: string | null; page: number; pageCount: number; totalCount: number }) {
 const router = useRouter(); const store = useCallersStore(); const selected = callers.find((row) => row.id === selectedId); const shown = store.revealed;
 const show = async (field: 'email' | 'name') => { if (!selected) return; const result = await reveal(api, { targetType: 'caller', targetId: selected.id, field, reasonCode: 'support_request' }); if (result.ok && typeof result.data.value === 'string') store.setRevealed(field, result.data.value); };
 return <ConsoleShell section="callers" heading={consoleCopy.callers.heading}><Banner tone="info" title={consoleCopy.callers.privacy} /><DataTable surface="page" caption={consoleCopy.callers.heading} data={callers} columns={callerColumns} getRowId={(row) => row.id} getRowHref={(row) => `/admin/callers/${row.id}`} selectedRowId={selectedId ?? undefined} emptyState={<Paragraph>{consoleCopy.callers.empty}</Paragraph>} /><Pagination page={page} pageCount={pageCount} totalCount={totalCount} pageSize={50} onPageChange={(next) => router.push(`/admin/callers?page=${next}`)} />{selected ? <Section testID="caller-detail"><Heading level={2}>{consoleCopy.callers.identity}</Heading><KeyValueList items={[{ key: 'id', label: 'Caller id', value: selected.id, action: <CopyButton value={selected.id} label="Copy Caller id" /> }, { key: 'email', label: 'Email', value: shown.email ? <MaskedValue state="revealed" value={shown.email} onHide={store.clearRevealed} /> : <MaskedValue state="masked" mask={selected.email} onRevealRequest={() => void show('email')} /> }, { key: 'name', label: 'Name', value: shown.name ? <MaskedValue state="revealed" value={shown.name} onHide={store.clearRevealed} /> : <MaskedValue state="masked" mask={selected.name} onRevealRequest={() => void show('name')} /> }, { key: 'age', label: 'Age band', value: selected.age }]} /><Button title={selected.deletionScheduledFor ? consoleCopy.callers.cancel : consoleCopy.callers.schedule} variant="danger" onPress={() => store.openDialog(selected.deletionScheduledFor ? 'cancel' : 'delete')} /><ConfirmDestructive open={store.dialog === 'delete'} title="Schedule deletion for this Caller?" consequences={["Their personal data is deleted after 7 days. Their Mons move into Dr. Santoro's care."]} confirmText={selected.id.slice(-6)} confirmLabel={consoleCopy.callers.schedule} reasonOptions={reasonOptions} onClose={store.closeDialog} onConfirm={async ({ reasonCode }) => { if (!reasonCode) throw fail(); const result = await scheduleCallerDeletion(api, selected.id, { reasonCode, confirmText: selected.id.slice(-6), expectedUpdatedAt: selected.updatedAt }); if (!result.ok) throw fail(); router.refresh(); }} /><ConfirmDestructive open={store.dialog === 'cancel'} title="Cancel deletion?" consequences={['The Caller keeps their account.']} confirmText={selected.id.slice(-6)} confirmLabel={consoleCopy.callers.cancel} onClose={store.closeDialog} onConfirm={async () => { const result = await cancelCallerDeletion(api, selected.id, { expectedUpdatedAt: selected.updatedAt }); if (!result.ok) throw fail(); router.refresh(); }} /></Section> : null}</ConsoleShell>;
}

type Consent = { id: string; parentEmail: string; age: string; status: string; expiresAt: string; emailsSent: number; updatedAt: string };
const consentColumns: ColumnDef<Consent, unknown>[] = [{ accessorKey: 'id', header: 'Consent' }, { accessorKey: 'status', header: 'Status' }, { accessorKey: 'expiresAt', header: 'Expires' }, { accessorKey: 'emailsSent', header: 'Emails sent' }];
export function ConsentViewClient({ consents, selectedId }: { consents: Consent[]; selectedId: string | null }) { const router = useRouter(); const store = useConsentStore(); const selected = consents.find((row) => row.id === selectedId); return <ConsoleShell section="consent" heading={consoleCopy.consent.heading}><Banner tone="info" title={consoleCopy.consent.rule} /><DataTable surface="page" caption={consoleCopy.consent.heading} data={consents} columns={consentColumns} getRowId={(row) => row.id} getRowHref={(row) => `/admin/consent/${row.id}`} selectedRowId={selectedId ?? undefined} />{selected ? <Section testID="consent-detail"><KeyValueList items={[{ key: 'email', label: "Parent's email", value: <MaskedValue state="masked" mask={selected.parentEmail} onRevealRequest={async () => { const result = await reveal(api, { targetType: 'consent', targetId: selected.id, field: 'parentEmail', reasonCode: 'parent_request' }); if (result.ok && typeof result.data.value === 'string') store.setRevealed('email', result.data.value); }} /> }, { key: 'status', label: 'Status', value: selected.status }, { key: 'age', label: "Child's age band", value: selected.age }]} /><Button title={consoleCopy.consent.resend} onPress={async () => { const result = await resendConsentEmail(api, selected.id); if (result.ok) router.refresh(); }} /><Button title={consoleCopy.consent.remove} variant="danger" onPress={() => store.openDialog('delete')} /><ConfirmDestructive open={store.dialog === 'delete'} title="Delete this consent record?" consequences={["The parent's email and the child's birth year are deleted now. A receipt stays."]} confirmText={selected.id.slice(-6)} confirmLabel="Delete record" reasonOptions={reasonOptions} onClose={store.closeDialog} onConfirm={async ({ reasonCode }) => { if (!reasonCode) throw fail(); const result = await deleteConsentRecord(api, selected.id, { reasonCode, confirmText: selected.id.slice(-6) }); if (!result.ok) throw fail(); router.push('/admin/consent'); router.refresh(); }} /></Section> : null}</ConsoleShell>; }

type Mon = { id: string; eggId: string; species: string; caller: string; stage: string; bond: number; confirmed: boolean }; type Egg = { id: string; species: string; caller: string; ends: number; hatched: boolean };
const monColumns: ColumnDef<Mon, unknown>[] = [{ accessorKey: 'id', header: 'Mon' }, { accessorKey: 'species', header: 'Species' }, { accessorKey: 'caller', header: 'Caller' }, { accessorKey: 'stage', header: 'Stage' }]; const eggColumns: ColumnDef<Egg, unknown>[] = [{ accessorKey: 'id', header: 'Egg' }, { accessorKey: 'species', header: 'Species' }, { accessorKey: 'caller', header: 'Caller' }, { accessorKey: 'hatched', header: 'Hatched' }];
export function MonsViewClient({ mons, eggs, run }: { mons: Mon[]; eggs: Egg[]; run: Integrity | null }) { const router = useRouter(); return <ConsoleShell section="mons" heading={consoleCopy.mons.heading}><Banner tone="neutral" title={consoleCopy.mons.readonly} /><Heading level={2}>Mons</Heading><DataTable surface="page" caption="Mons" data={mons} columns={monColumns} getRowId={(row) => row.id} /><Heading level={2}>Eggs</Heading><DataTable surface="page" caption="Eggs" data={eggs} columns={eggColumns} getRowId={(row) => row.id} /><Heading level={2}>{consoleCopy.mons.integrity}</Heading><Checklist>{([['shared_egg', 'Mons sharing one egg', run?.sharedEgg], ['id_mismatch', "Mon ids that don't match their egg", run?.idMismatch], ['orphans', 'Hatched eggs with no Mon, or Mons whose egg isn’t hatched', run?.orphans], ['stale_ready', 'Eggs ready for more than 7 days', run?.staleReady]] as const).map(([key, label, count]) => <CheckRow key={key} label={label} result={count === undefined ? { kind: 'unavailable', reason: 'No check has run' } : count === 0 ? { kind: 'pass', count: 0 } : { kind: 'fail', count }} />)}</Checklist><Button title="Run check" onPress={async () => { const result = await runIntegrityCheck(api); if (result.ok) router.refresh(); }} /></ConsoleShell>; }

export function ContentViewClient() { return <ConsoleShell section="content" heading={consoleCopy.content.heading}><Banner tone="info" title={consoleCopy.content.banner} /><Card surface="page" title="Bloodlines" description="Content records are read from the authored package at build time." /></ConsoleShell>; }

type AuditRow = EventRow & { actor: string; reason: string }; const auditColumns: ColumnDef<AuditRow, unknown>[] = [{ accessorKey: 'at', header: 'When' }, { accessorKey: 'action', header: 'Action' }, { accessorKey: 'target', header: 'Target' }, { accessorKey: 'actor', header: 'Staff' }, { accessorKey: 'reason', header: 'Reason' }];
export function AuditViewClient({ events, selectedId }: { events: AuditRow[]; selectedId: string | null }) { const selected = events.find((row) => row.id === selectedId); return <ConsoleShell section="audit" heading={consoleCopy.audit.heading}><Banner tone="neutral" title={consoleCopy.audit.rule} action={<Link href="/payload-api/console/audit/export">{consoleCopy.audit.export}</Link>} /><DataTable surface="page" caption={consoleCopy.audit.heading} data={events} columns={auditColumns} getRowId={(row) => row.id} getRowHref={(row) => `/admin/audit/${row.id}`} selectedRowId={selectedId ?? undefined} />{selected ? <KeyValueList items={[{ key: 'when', label: 'When', value: selected.at }, { key: 'who', label: 'Who', value: selected.actor }, { key: 'what', label: 'What', value: selected.action }, { key: 'why', label: 'Why', value: selected.reason }]} /> : null}</ConsoleShell>; }

type Staff = { id: string; email: string; role: string }; const staffColumns: ColumnDef<Staff, unknown>[] = [{ accessorKey: 'email', header: 'Email' }, { accessorKey: 'role', header: 'Role' }];
export function SettingsViewClient({ staff, isOps }: { staff: Staff[]; isOps: boolean }) { const router = useRouter(); const store = useSettingsStore(); const selected = staff.find((row) => row.id === store.selectedId); return <ConsoleShell section="settings" heading={consoleCopy.settings.heading}><Heading level={2}>{consoleCopy.settings.appearance}</Heading><Paragraph>Match system</Paragraph><Heading level={2}>{consoleCopy.settings.staff}</Heading><DataTable surface="page" caption={consoleCopy.settings.staff} data={staff} columns={staffColumns} getRowId={(row) => row.id} selection={isOps ? { selectedIds: store.selectedId ? [store.selectedId] : [], onSelectedIdsChange: (ids) => store.setSelectedId(ids[0] ?? null) } : undefined} />{selected && isOps ? <><Button title={consoleCopy.settings.remove} variant="danger" onPress={() => store.openDialog('remove')} /><ConfirmDestructive open={store.dialog === 'remove'} title="Remove staff access?" consequences={['This person can no longer use the console.']} confirmText={selected.id.slice(-6)} confirmLabel={consoleCopy.settings.remove} reasonOptions={reasonOptions} onClose={store.closeDialog} onConfirm={async ({ reasonCode }) => { if (!reasonCode) throw fail(); const result = await removeStaff(api, selected.id, { reasonCode }); if (!result.ok) throw fail(); store.setSelectedId(null); router.refresh(); }} /></> : null}</ConsoleShell>; }
