/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayloadRouteImport } from './routes/_payload'
import { Route as PayloadAdminIndexRouteImport } from './routes/_payload/admin.index'
import { Route as PayloadAdminSplatRouteImport } from './routes/_payload/admin.$'
import { Route as PayloadPayloadApiSplatRouteImport } from './routes/_payload/payload-api.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadRoute = PayloadRouteImport.update({
  id: '/_payload',
  getParentRoute: () => rootRouteImport,
} as any)
const PayloadAdminIndexRoute = PayloadAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadAdminSplatRoute = PayloadAdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => PayloadRoute,
} as any)
const PayloadPayloadApiSplatRoute = PayloadPayloadApiSplatRouteImport.update({
  id: '/payload-api/$',
  path: '/payload-api/$',
  getParentRoute: () => PayloadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/payload-api/$': typeof PayloadPayloadApiSplatRoute
  '/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/$': typeof PayloadAdminSplatRoute
  '/payload-api/$': typeof PayloadPayloadApiSplatRoute
  '/admin': typeof PayloadAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_payload': typeof PayloadRouteWithChildren
  '/_payload/admin/$': typeof PayloadAdminSplatRoute
  '/_payload/payload-api/$': typeof PayloadPayloadApiSplatRoute
  '/_payload/admin/': typeof PayloadAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin/$' | '/payload-api/$' | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin/$' | '/payload-api/$' | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_payload'
    | '/_payload/admin/$'
    | '/_payload/payload-api/$'
    | '/_payload/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PayloadRoute: typeof PayloadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload': {
      id: '/_payload'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PayloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_payload/admin/': {
      id: '/_payload/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof PayloadAdminIndexRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/admin/$': {
      id: '/_payload/admin/$'
      path: '/admin/$'
      fullPath: '/admin/$'
      preLoaderRoute: typeof PayloadAdminSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
    '/_payload/payload-api/$': {
      id: '/_payload/payload-api/$'
      path: '/payload-api/$'
      fullPath: '/payload-api/$'
      preLoaderRoute: typeof PayloadPayloadApiSplatRouteImport
      parentRoute: typeof PayloadRoute
    }
  }
}

interface PayloadRouteChildren {
  PayloadAdminSplatRoute: typeof PayloadAdminSplatRoute
  PayloadPayloadApiSplatRoute: typeof PayloadPayloadApiSplatRoute
  PayloadAdminIndexRoute: typeof PayloadAdminIndexRoute
}

const PayloadRouteChildren: PayloadRouteChildren = {
  PayloadAdminSplatRoute: PayloadAdminSplatRoute,
  PayloadPayloadApiSplatRoute: PayloadPayloadApiSplatRoute,
  PayloadAdminIndexRoute: PayloadAdminIndexRoute,
}

const PayloadRouteWithChildren =
  PayloadRoute._addFileChildren(PayloadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PayloadRoute: PayloadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
