// Screen copy for M01–M07, keyed by docs/COPY_DECK.md ids and drafted in
// docs/design/screens/Mxx/05-copy.md. Change a string there first, then here.
// Shared namespaces: `m23.*` (the hatch notification, defined in M06),
// `m11.*` (M11 status rows M06 triggers), `mail.*` (server email), `inbox.*`
// (the notifications tab).

export const ONBOARDING_COPY = {
  'm01.a11y.power_on': 'H-Lynk on',

  // M06 — notification permission sheet over M10 (screens/M06/05-copy.md)
  'm06.preview.app_name': 'NYC-MON',
  'm06.preview.time': 'now',
  'm06.preview.a11y.label': 'Example notification from NYC-MON: Your egg is ready to hatch.',
  'm06.title': 'One notification when your egg is ready',
  'm06.body.15': "That's in about 15 minutes. It's the only one we send, and your egg waits for you either way.",
  'm06.body.30': "That's in about 30 minutes. It's the only one we send, and your egg waits for you either way.",
  'm06.body.60': "That's in about an hour. It's the only one we send, and your egg waits for you either way.",
  'm06.cta.allow': 'Turn on notifications',
  'm06.cta.later': 'Not now',
  'm06.grabber.a11y.label': 'Close',
  'm06.granted.a11y.announce': 'Notifications on.',

  // M23 — the one notification per egg, ever (screens/M06/05-copy.md)
  'm23.notification.title': 'Your egg is ready to hatch',
  'm23.notification.body': "Open NYC-MON whenever you're ready.",

  // M11 status rows that M06 triggers (screens/M06/05-copy.md)
  'm11.status.notify_off': 'Notifications are off. Open the app to check on your egg.',
  'm11.status.notify_off.action.ask': 'Turn on',
  'm11.status.notify_off.action.settings': 'Open Settings',
  'm11.status.notify_off.action.settings.a11y.hint': "Opens NYC-MON in your phone's Settings",
  'm11.status.schedule_failed': "We couldn't set the notification. Open the app to check on your egg.",

  // The notifications tab (drawer + site). NYC-MON sends one notification
  // per egg, so the honest inbox is empty until the first egg is ready.
  'inbox.title': 'Notifications',
  'inbox.unread': '{count} unread',
  'inbox.mark_all_read': 'Mark all read',
  'inbox.today': 'Today',
  'inbox.earlier': 'Earlier',
  'inbox.empty.title': 'Nothing yet',
  'inbox.empty.body': 'When your egg is ready, it shows up here.',

  'm02.carousel.label': 'Welcome',
  'm02.skip': 'Skip',
  'm02.skip.a11y.hint': 'Goes to the last page',
  'm02.next': 'Next',
  'm02.prev.a11y.label': 'Previous',
  'm02.next.a11y.label': 'Next',
  'm02.progress.a11y': 'Page {n} of 3',
  'm02.p1.title': 'Mons live in New York, on the same blocks as you.',
  'm02.p1.body': "They showed up less than ten years ago. The city's still figuring them out.",
  'm02.p1.image.alt': 'A Harlem street of brownstones with stoops out front.',
  'm02.p2.title': 'Three eggs. One of them hatches for you.',
  'm02.p2.body': "Each comes from a Bloodline. Whoever's inside is their own person.",
  'm02.p2.caption.f01': 'Hood Ratti Bloodline',
  'm02.p2.caption.f02': 'Bodega Baddiee Cee Bloodline',
  'm02.p2.caption.f12': 'Yote Bloodline',
  'm02.p2.image.alt': 'Three eggs side by side: Metro Egg, Hood Ratti Bloodline. Corner Egg, Bodega Baddiee Cee Bloodline. Prism Egg, Yote Bloodline.',
  'm02.p3.title': "You'd be their Caller.",
  'm02.p3.body.a': "A Caller is a Mon's partner. Mons think for themselves, and they can say no.",
  'm02.p3.body.b': "Scanning isn't recruiting. A Mon decides who it partners with.",
  'm02.p3.image.alt': 'The H-Lynk: a red handheld with a black scanner along the top.',
  'm02.p3.cta.primary': 'Get started',
  'm02.p3.cta.primary.a11y.hint': 'Sets up a new account',
  'm02.p3.cta.secondary': 'Already a Caller? Sign in',
  'm02.p3.cta.secondary.a11y.hint': 'For players who already have an account',
  'm02.status.offline': "You're offline. You won't need a connection until you sign in.",

  'm04.title': 'What year were you born?',
  'm04.why': 'We ask everyone this once.',
  'm04.back.a11y.label': 'Back',
  'm04.grid.decades.a11y.label': 'Decades',
  'm04.decade.a11y.hint': 'Shows the years in that decade',
  'm04.grid.years.a11y.label': 'Years in the {decade}s',
  'm04.change_decade': 'Change decade',
  'm04.type_instead': 'Type it instead',
  'm04.field.label': 'Birth year',
  'm04.field.hint': 'Four digits',
  'm04.pick_instead': 'Pick from a list instead',
  'm04.error.incomplete': 'Enter all four digits of the year.',
  'm04.error.future': "That year hasn't happened yet. Check the number.",
  'm04.error.too_early': 'Check that year. It needs to be 1900 or later.',
  'm04.continue': 'Continue',
  'm04.continue.a11y.hint': 'Saves {year} as your birth year',

  'm07.title': 'What should your Mon call you?',
  'm07.field.label': 'Caller name',
  'm07.field.hint': 'A nickname works.',
  'm07.field.hint.under13': 'Use a nickname, not your real name.',
  'm07.field.hint.pending': 'Use a nickname, not your real name. It stays on this phone until your parent or guardian says yes.',
  'm07.field.clear.a11y.label': 'Clear name',
  'm07.plate.a11y.label': 'Caller name preview: {name}',
  'm07.continue': 'Use this name',
  'm07.continue.a11y.hint.disabled': 'Type a name first',
  'm07.back.a11y.label': 'Back',
  'm07.error.blank': 'Add at least one letter.',
  'm07.error.too_long': "That's more than 16 characters. Try a shorter version.",
  'm07.error.characters': 'Names can use letters, spaces, hyphens, apostrophes and periods.',
  'm07.error.blocked': 'Our filter blocked that name. It gets things wrong sometimes, so try a nickname for now.',
  'm07.confirmed.a11y.announce': 'Caller name saved.',

  'm03.title.create': 'Make your account',
  'm03.title.sign_in': 'Sign in',
  'm03.subtitle.create': 'Your account keeps your Mon with you if you switch phones.',
  'm03.subtitle.sign_in': 'Pick the way you signed up, and your Mon comes with you.',
  'm03.switch.to_create': 'New here? Get started',
  'm03.switch.to_sign_in': 'Already a Caller? Sign in',
  'm03.provider.passkey.a11y.hint.ios': 'Uses Face ID, Touch ID or your passcode. No password.',
  'm03.provider.passkey.a11y.hint.android': 'Uses your fingerprint, face or screen lock. No password.',
  'm03.email.loading': 'Signing you in…',
  'm03.email.loading.create': 'Making your account…',
  'm03.email.field.label': 'Email',
  'm03.password.field.label': 'Password',
  'm03.password.field.hint.create': 'At least 10 characters',
  'm03.password.show.a11y.label': 'Show password',
  'm03.password.hide.a11y.label': 'Hide password',
  'm03.email.submit.create': 'Make account',
  'm03.email.submit.sign_in': 'Sign in',
  'm03.password.forgot': 'Forgot password?',
  'm03.error.passkey.not_found': 'No NYC-MON passkey on this phone. Try another way to sign in.',
  'm03.error.passkey.failed': "That passkey didn't work. Try again, or pick another way.",
  'm03.error.email.invalid': 'That email looks off. Check it for a typo.',
  'm03.error.credentials': "That email and password don't match. Check both, or reset your password.",
  'm03.error.password.too_short': 'Use at least 10 characters.',
  'm03.error.password.too_long': 'That password is too long. Try a shorter one.',
  'm03.error.account_exists': 'That email already has an account. Sign in instead.',
  'm03.error.not_verified': 'Confirm your email first. We just sent a new link.',
  'm03.error.offline': "You're offline. Connect to the internet to sign in.",
  'm03.error.server': 'Something broke on our end. Try again in a minute.',
  'm03.verify.title': 'Check your email',
  'm03.verify.body': 'We sent a link to {email}. Open it to finish making your account.',
  'm03.verify.resend': 'Send it again',
  'm03.verify.change_email': 'Change email',
  'm03.verify.resent': 'Sent again. It can take a few minutes, and it sometimes lands in spam.',
  'm03.verify.resend.wait': 'You can send it again in {seconds} s',
  'm03.verify.stuck': 'Still nothing? Try Apple, Google or a passkey instead.',
  'm03.provider.apple.label.create': 'Sign up with Apple',
  'm03.provider.apple.label.sign_in': 'Sign in with Apple',
  'm03.provider.google.label.create': 'Sign up with Google',
  'm03.provider.google.label.sign_in': 'Sign in with Google',
  'm03.provider.passkey.label.create': 'Make a passkey',
  'm03.provider.passkey.label.sign_in': 'Sign in with a passkey',
  'm03.provider.email.label': 'Continue with email',
  'm03.provider.apple.loading': 'Waiting for Apple…',
  'm03.provider.google.loading': 'Waiting for Google…',
  'm03.provider.passkey.loading': 'Checking your passkey…',
  'm03.error.google.failed': "Google sign-in didn't go through. Try again, or pick another way.",
  'm03.error.apple.failed': "Apple sign-in didn't go through. Try again, or pick another way.",
  'm03.reset.title': 'Reset your password',
  'm03.reset.body': "Enter your email. If it has an account, we'll send a link.",
  'm03.reset.submit': 'Send link',
  'm03.reset.sent': 'If that email has an account, the link is on its way. It works for one hour.',
  'm03.reset.unavailable': "Password reset isn't working right now. Try another way to sign in.",
  'm03.legal.notice.create': 'By making an account, you agree to the Terms and the Privacy Policy.',
  'm03.back.a11y.label': 'Go back',
  'm03.legal.terms': 'Terms',
  'm03.legal.privacy': 'Privacy Policy',
  'm03.legal.children': "Children's privacy",

  'm05.ask.title': 'You can keep playing',
  'm05.ask.body': "A parent or guardian needs to say yes to your account. We'll email them. Until they do, your game stays on this phone.",
  'm05.field.label': "Parent or guardian's email",
  'm05.field.hint': 'We only use it to ask them.',
  'm05.preview.toggle': "See the email we'll send",
  'm05.preview.toggle.a11y.hint': 'Shows the whole email',
  'm05.send': 'Send email',
  'm05.send.loading': 'Sending…',
  'm05.error.email.invalid': 'That email looks off. Check it for a typo.',
  'm05.error.offline': "You're offline, so the email can't go out yet. Try again when you're connected.",
  'm05.error.server': "That didn't send. Try again in a minute.",
  'm05.sent.title': 'Email sent',
  'm05.sent.body': 'We sent it to {email}. Once they say yes, your account is ready. Keep playing in the meantime.',
  'm05.sent.continue': 'Keep playing',
  'm05.sent.resend': 'Send it again',
  'm05.sent.change_email': 'Change email',
  'm05.badge.pending': 'Waiting for a grown-up',
  'm05.badge.pending.a11y': 'Your account is waiting for a parent or guardian to say yes.',
  'm05.denied.title.no_mon': 'Your parent or guardian said no',
  'm05.denied.body.no_mon': "That's their call, and you didn't do anything wrong. We've deleted everything this app saved about you. If they change their mind later, you can start fresh.",
  'm05.denied.close': 'Close',

  'mail.consent.subject': 'Your child asked to set up an NYC-MON account',
  'mail.consent.body.intro': 'Hi. Someone entered this email address in the NYC-MON app and asked you to approve an account for a child under 13.',
  'mail.consent.body.what': 'NYC-MON is a game set in New York. Players look after a creature called a Mon on their phone. The game calls players Callers.',
  'mail.consent.body.keep': "If you say yes, we keep your child's birth year, the Caller name they choose and their Mon's progress, so the game works on a new phone.",
  'mail.consent.body.dont': 'We show no ads based on what your child does, and the only notification is sent by the phone itself when an egg is ready.',
  'mail.consent.body.no': "If you say no, we delete your email address and everything your child saved with us. In the game, their Mon goes to stay with one of the characters, so your child doesn't see it deleted.",
  'mail.consent.body.silence': "If you don't answer within {days} days, we delete this request and your email address.",
  'mail.consent.footer': "You got this email because someone typed your address into NYC-MON. If you don't know who, you can ignore it and we'll delete it in {days} days.",
} as const;

export type OnboardingCopyId = keyof typeof ONBOARDING_COPY;

/** Fills `{token}` placeholders in a copy string. */
export function copy(id: OnboardingCopyId, tokens?: Record<string, string | number>): string {
  let text: string = ONBOARDING_COPY[id];
  if (tokens) {
    for (const [key, value] of Object.entries(tokens)) text = text.replaceAll(`{${key}}`, String(value));
  }
  return text;
}
