import type { z } from 'zod';
import type * as S from '../schemas/index.ts';

export type LifecycleStage = z.infer<typeof S.LifecycleStageSchema>;
export type IdleVignetteDef = z.infer<typeof S.IdleVignetteDefSchema>;
export type MonSpeciesDef = z.infer<typeof S.MonSpeciesDefSchema>;
export type MonInstance = z.infer<typeof S.MonInstanceSchema>;
export type ConsentStatus = z.infer<typeof S.ConsentStatusSchema>;
export type CallerProfile = z.infer<typeof S.CallerProfileSchema>;
export type CareNeed = z.infer<typeof S.CareNeedSchema>;
export type CareActivity = z.infer<typeof S.CareActivitySchema>;
export type CareRequest = z.infer<typeof S.CareRequestSchema>;
export type CareState = z.infer<typeof S.CareStateSchema>;
export type CareAction = z.infer<typeof S.CareActionSchema>;
export type IncubationMinutes = z.infer<typeof S.IncubationMinutesSchema>;
export type EggRecord = z.infer<typeof S.EggRecordSchema>;
export type HatchPresentationPhase = z.infer<typeof S.HatchPresentationPhaseSchema>;
export type HatchState = z.infer<typeof S.HatchStateSchema>;
export type EvolutionEvent = z.infer<typeof S.EvolutionEventSchema>;
export type Affinity = z.infer<typeof S.AffinitySchema>;
export type CombatClass = z.infer<typeof S.CombatClassSchema>;
export type CombatStatus = z.infer<typeof S.CombatStatusSchema>;
export type BattleClipId = z.infer<typeof S.BattleClipIdSchema>;
export type SurfaceKind = z.infer<typeof S.SurfaceKindSchema>;
export type VoiceStage = z.infer<typeof S.VoiceStageSchema>;
export type VoiceLineage = z.infer<typeof S.VoiceLineageSchema>;
export type HoodEncounter = z.infer<typeof S.HoodEncounterSchema>;
export type CreateEggRequest = z.infer<typeof S.CreateEggRequestSchema>;
export type CreateEggResponse = z.infer<typeof S.CreateEggResponseSchema>;
export type HatchEggResponse = z.infer<typeof S.HatchEggResponseSchema>;
export type ListMyMonsResponse = z.infer<typeof S.ListMyMonsResponseSchema>;
export type CareWrite = z.infer<typeof S.CareWriteSchema>;
export type PutCareRequest = z.infer<typeof S.PutCareRequestSchema>;
export type PutCareResponse = z.infer<typeof S.PutCareResponseSchema>;
export type WriteQueue = z.infer<typeof S.WriteQueueSchema>;
export type SaveV1 = z.infer<typeof S.SaveV1Schema>;
export type SaveCurrent = z.infer<typeof S.SaveCurrentSchema>;
