import { baseConfig } from '@acme/config/eslint/base.mjs';

export default [
  ...baseConfig(),
  // FORBID_BACKEND_DIRECT (packages/config/eslint/boundaries.mjs) keeps
  // `payload` and `@payloadcms/*` out of feature code. This whole app is the
  // Payload host, so it is the exempt server code.
  {
    files: ['src/**', 'vite.config.ts'],
    rules: { 'no-restricted-imports': 'off' },
  },
  // Generated by `pnpm --filter admin-vite payload:importmap`: one import
  // statement per registered component, rewritten on every regeneration.
  {
    files: ['src/routes/_payload/importMap.js'],
    rules: { 'import/no-duplicates': 'off' },
  },
  { ignores: ['dist/**', '.output/**', '.vercel/**', '.tanstack/**', 'src/routeTree.gen.ts'] },
];
